import {
  ClockIcon,
  CompassIcon,
  ConfettiIcon,
  CrosshairIcon,
  DiceFiveIcon,
  FileTextIcon,
  FireIcon,
  LightningIcon,
  MedalIcon,
  MetronomeIcon,
  MoonStarsIcon,
  PersonSimpleRunIcon,
  SparkleIcon,
  StackIcon,
  SunHorizonIcon,
  SwordIcon,
  TargetIcon,
  TimerIcon,
  TrendUpIcon,
  TrophyIcon,
} from "@phosphor-icons/react";

export const achievementIcons = {
  archive: StackIcon,
  "biceps-flexed": SwordIcon,
  "chart-no-axes-column": MetronomeIcon,
  clock: ClockIcon,
  compass: CompassIcon,
  dices: DiceFiveIcon,
  dumbbell: PersonSimpleRunIcon,
  "file-text": FileTextIcon,
  flame: FireIcon,
  footprints: PersonSimpleRunIcon,
  medal: MedalIcon,
  moon: MoonStarsIcon,
  orbit: CrosshairIcon,
  "party-popper": ConfettiIcon,
  sparkles: SparkleIcon,
  sunrise: SunHorizonIcon,
  target: TargetIcon,
  timer: TimerIcon,
  "trending-up": TrendUpIcon,
  trophy: TrophyIcon,
  zap: LightningIcon,
} as const;

export type AchievementIconName = keyof typeof achievementIcons;
