import { launchFixtureBrowser, artifactPath, assertBrowserClean } from "../runtime.mjs";
import { expect } from "@playwright/test";
const browser = await launchFixtureBrowser();
const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});
await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
page.on('pageerror',e=>console.log('PAGE ERROR',e.message));
await page.goto('http://127.0.0.1:4317/?area&resume&paused');
const input=page.locator('input[type=text]');
await expect(input).toHaveValue('ca');await expect(input).toBeDisabled();
await page.waitForTimeout(250);
console.log('paused restore reports',await page.evaluate(()=>window.__areaReports.length));
await page.getByRole('button',{name:'Resume fixture'}).click();await page.waitForTimeout(250);
console.log('resumed exact input/time',await page.locator('[data-area-stats]').innerText());
await page.getByRole('button',{name:'Pause fixture'}).click();await page.waitForTimeout(100);
const count=await page.evaluate(()=>window.__areaReports.length);
await page.getByRole('button',{name:'Rerender fixture'}).click();await page.waitForTimeout(300);
expect(await page.evaluate(()=>window.__areaReports.length)).toBe(count);
await page.goto('http://127.0.0.1:4317/?area');await input.waitFor();
await input.fill('cattt d');expect(await page.evaluate(()=>window.__areaFinishes.length)).toBe(0);
await expect(page.locator('[data-typing-caret]')).toHaveCount(1);
await input.press('Home');expect(await input.evaluate(el=>el.selectionStart)).toBe(7);
await input.press('Tab');expect(await input.evaluate(el=>document.activeElement===el)).toBe(false);
await input.fill('cattt dog');await page.waitForTimeout(100);
expect(await page.evaluate(()=>window.__areaFinishes.length)).toBe(1);
await page.goto('http://127.0.0.1:4317/?area&long');await input.waitFor();
const long='supercalifragilisticexpialidocious'.repeat(3);
await input.fill(long.slice(0,70));await page.waitForTimeout(150);
console.log('long wrapped caret',await page.locator('[data-typing-caret]').boundingBox(),'viewport',await page.locator('[data-typing-caret]').evaluate(el=>{let p=el.parentElement;while(p&&getComputedStyle(p).overflow!=='hidden')p=p.parentElement;return p?.getBoundingClientRect().toJSON();}));
console.log('long document overflow',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
await page.screenshot({path:artifactPath("practice-area-long-narrow.png")});
await page.goto('http://127.0.0.1:4317/?area&long&tape');await input.waitFor();
for(let i=1;i<70;i+=4) await input.fill(long.slice(0,i));
await page.waitForTimeout(200);
console.log('tape caret bounds',await page.locator('[data-typing-caret]').boundingBox());
await assertBrowserClean(browser); await browser.close();
