import { launchFixtureBrowser, artifactPath, assertBrowserClean } from "../runtime.mjs";
import { expect } from "@playwright/test";
const browser = await launchFixtureBrowser();
const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});
await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
page.on('pageerror',e=>console.log('PAGE ERROR',e.message));
await page.goto('http://127.0.0.1:4317/?color');
const trigger=page.getByRole('button',{name:'Pick color'}).first();
await trigger.click();
const dialog=page.getByRole('dialog',{name:'Color picker'});
await expect(dialog).toBeVisible();
await page.waitForTimeout(100);
console.log('narrow scrolled bounds',await dialog.boundingBox());
const hue=page.getByRole('slider',{name:'Hue'});await hue.focus();await page.keyboard.press('PageUp');
console.log('keyboard hue',await hue.getAttribute('aria-valuenow'));
const box=await hue.boundingBox();await page.touchscreen.tap(box.x+box.width-5,box.y+box.height/2);
console.log('touch hue',await hue.getAttribute('aria-valuenow'));
await page.screenshot({path:artifactPath("practice-color-narrow.png"),fullPage:false});
await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(trigger).toBeFocused();
for(let i=0;i<4;i++){await trigger.click();await page.keyboard.press('Escape');}
console.log('repeated open/close and Escape focus passed');
await assertBrowserClean(browser); await browser.close();
